version: '3.8'

services:
  my-node-app:
    container_name: my-node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 5
